Added an alias for indexing by groups
yiisoft/arrays pull request #91
Opened 2021-02-18 07:31 UTC by sagittaracc

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2021-02-18 07:55 UTC, vjik requested changes
Can you add tests for this method?

2021-02-18 07:55 UTC, vjik commented on src/ArrayHelper.php
> +     *
```suggestion
     *
     * @psalm-param array<mixed, array|object> $array
     *
```

2021-02-18 08:57 UTC, sagittaracc commented on src/ArrayHelper.php
> +     *
I did

2021-02-18 12:52 UTC, vjik approved these changes

2021-02-19 07:23 UTC, samdark approved these changes

2021-02-19 07:23 UTC, merged

2021-02-19 07:23 UTC, samdark commented
Thanks.